export const SET_TM='SET_TM';
export const SET_SHOWGUIDE='SET_SHOWGUIDE'
export const SET_SHOWMOREGROUP='SET_SHOWMOREGROUP'
export const SET_GROUPS='SET_GROUPS'
export const SET_FREEBUY='SET_FREEBUY'
export const SET_MODALOPEN='SET_MODALOPEN'
export const SET_SHOWCOUPONBUY='SET_SHOWCOUPONBUY'
export const SET_COUPONBUYFILTER='SET_COUPONBUYFILTER'
export const SET_COUPONS='SET_COUPONS';
export const SET_CANTUANPRICE='SET_CANTUANPRICE';
export const SET_BUYMODE='SET_BUYMODE';
export const SET_GROUPID='SET_GROUPID';
export const SET_COUPONID='SET_COUPONID';

export const SET_PAGEDATA='SET_PAGEDATA'
